version: '2'
services:
  elasticsearch:
    image: elasticsearch:2
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"

  logstash:
    build: logstash/
    ports:
      - "5000:5000"
      - "5044:5044"
    depends_on:
      - elasticsearch

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - elasticsearch

networks:
  default:
    driver: bridge
